export const SET_APARTMENTS_LIST = 'SET_APARTMENTS_LIST';
export const FETCH_APARTMENTS_LIST = 'FETCH_APARTMENTS_LIST';
export const SET_CURRENT_APARTMENT = 'SET_CURRENT_APARTMENT';
export const FETCH_CURRENT_APARTMENT = 'FETCH_CURRENT_APARTMENT';
